// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"banking-microservices/pkg/common/config"
	"banking-microservices/pkg/common/database"
	"banking-microservices/services/audit-service/handlers"
	"banking-microservices/services/audit-service/repository"
	"banking-microservices/services/audit-service/service"
	"github.com/gofiber/fiber/v3"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeApp wires dependencies and initializes the Fiber App
func InitializeApp(cfg *config.Config) (*fiber.App, error) {
	db, err := database.ProvideDB(cfg)
	if err != nil {
		return nil, err
	}
	auditRepository, err := repository.ProvideAuditRepository(db)
	if err != nil {
		return nil, err
	}
	auditService := service.NewAuditService(auditRepository)
	auditHandler := handlers.NewAuditHandler(auditService)
	app := ProvideApp(auditHandler, cfg)
	return app, nil
}

// wire.go:

// AuditSet bundles all providers required for Audit Service
var AuditSet = wire.NewSet(database.ProviderSet, repository.ProviderSet, service.ProviderSet, handlers.NewAuditHandler, ProvideApp)
