// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"banking-microservices/pkg/client"
	"banking-microservices/pkg/common/config"
	"banking-microservices/pkg/common/database"
	"banking-microservices/services/auth-service/handlers"
	"banking-microservices/services/auth-service/repository"
	"banking-microservices/services/auth-service/service"
	"github.com/gofiber/fiber/v3"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeApp wires dependencies and initializes the Fiber App
func InitializeApp(cfg *config.Config) (*fiber.App, error) {
	db, err := database.ProvideDB(cfg)
	if err != nil {
		return nil, err
	}
	authRepository, err := repository.ProvideAuthRepository(db)
	if err != nil {
		return nil, err
	}
	auditClient := client.ProvideAuditClient(cfg)
	authService := service.ProvideAuthService(authRepository, cfg, auditClient)
	authHandler := handlers.NewAuthHandler(authService)
	app := ProvideApp(authHandler, cfg)
	return app, nil
}

// wire.go:

// AuthSet bundles all providers required for Auth Service
var AuthSet = wire.NewSet(database.ProviderSet, client.ProviderSet, repository.ProviderSet, service.ProviderSet, handlers.NewAuthHandler, ProvideApp)
