// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"banking-microservices/pkg/client"
	"banking-microservices/pkg/common/config"
	"banking-microservices/pkg/common/database"
	"banking-microservices/services/account-service/handlers"
	"banking-microservices/services/account-service/repository"
	"banking-microservices/services/account-service/service"
	"github.com/gofiber/fiber/v3"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeApp wires dependencies and initializes the Fiber App
func InitializeApp(cfg *config.Config) (*fiber.App, error) {
	db, err := database.ProvideDB(cfg)
	if err != nil {
		return nil, err
	}
	accountRepository, err := repository.ProvideAccountRepository(db)
	if err != nil {
		return nil, err
	}
	auditClient := client.ProvideAuditClient(cfg)
	accountService := service.NewAccountService(accountRepository, auditClient)
	accountHandler := handlers.NewAccountHandler(accountService)
	app := ProvideApp(accountHandler, cfg)
	return app, nil
}

// wire.go:

// AccountSet bundles all providers required for Account Service
var AccountSet = wire.NewSet(database.ProviderSet, client.ProviderSet, repository.ProviderSet, service.ProviderSet, handlers.NewAccountHandler, ProvideApp)
