// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"banking-microservices/pkg/common/config"
	"github.com/gofiber/fiber/v3"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeGateway wires dependencies and initializes the API Gateway Fiber App
func InitializeGateway(cfg *config.Config) (*fiber.App, error) {
	app := ProvideGatewayApp(cfg)
	return app, nil
}

// wire.go:

// GatewaySet bundles all providers required for Gateway
var GatewaySet = wire.NewSet(
	ProvideGatewayApp,
)
