// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"banking-microservices/pkg/client"
	"banking-microservices/pkg/common/config"
	"banking-microservices/pkg/common/database"
	"banking-microservices/services/notification-service/grpc"
	"banking-microservices/services/notification-service/handlers"
	"banking-microservices/services/notification-service/repository"
	"banking-microservices/services/notification-service/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeServer wires all dependencies and returns the complete server bundle
func InitializeServer(cfg *config.Config) (*ServerBundle, error) {
	db, err := database.ProvideDB(cfg)
	if err != nil {
		return nil, err
	}
	notificationRepository, err := repository.ProvideNotificationRepository(db)
	if err != nil {
		return nil, err
	}
	auditClient := client.ProvideAuditClient(cfg)
	notificationService := service.NewNotificationService(notificationRepository, auditClient)
	notificationHandler := handlers.NewNotificationHandler(notificationService)
	app := ProvideApp(notificationHandler, cfg)
	notificationGRPCServer := grpc.NewNotificationGRPCServer(notificationService)
	server := ProvideGRPC(notificationGRPCServer)
	serverBundle := ProvideServerBundle(app, server)
	return serverBundle, nil
}

// wire.go:

// NotificationSet bundles all providers required for Notification Service
var NotificationSet = wire.NewSet(database.ProviderSet, client.ProviderSet, repository.ProviderSet, service.ProviderSet, grpc.ProviderSet, handlers.ProviderSet, ProvideApp,
	ProvideGRPC,
	ProvideServerBundle,
)
