// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"banking-microservices/pkg/client"
	"banking-microservices/pkg/common/config"
	"banking-microservices/pkg/common/database"
	"banking-microservices/services/customer-service/handlers"
	"banking-microservices/services/customer-service/repository"
	"banking-microservices/services/customer-service/service"
	"github.com/gofiber/fiber/v3"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeApp wires dependencies and initializes the Fiber App
func InitializeApp(cfg *config.Config) (*fiber.App, error) {
	db, err := database.ProvideDB(cfg)
	if err != nil {
		return nil, err
	}
	customerRepository, err := repository.ProvideCustomerRepository(db)
	if err != nil {
		return nil, err
	}
	auditClient := client.ProvideAuditClient(cfg)
	customerService := service.NewCustomerService(customerRepository, auditClient)
	customerHandler := handlers.NewCustomerHandler(customerService)
	app := ProvideApp(customerHandler, cfg)
	return app, nil
}

// wire.go:

// CustomerSet bundles all providers required for Customer Service
var CustomerSet = wire.NewSet(database.ProviderSet, client.ProviderSet, repository.ProviderSet, service.ProviderSet, handlers.NewCustomerHandler, ProvideApp)
