// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"banking-microservices/pkg/client"
	"banking-microservices/pkg/common/config"
	"banking-microservices/pkg/common/database"
	"banking-microservices/services/transaction-service/handlers"
	"banking-microservices/services/transaction-service/repository"
	"banking-microservices/services/transaction-service/service"
	"github.com/gofiber/fiber/v3"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeApp wires dependencies and initializes the Fiber App
func InitializeApp(cfg *config.Config) (*fiber.App, error) {
	db, err := database.ProvideDB(cfg)
	if err != nil {
		return nil, err
	}
	transactionRepository, err := repository.ProvideTransactionRepository(db)
	if err != nil {
		return nil, err
	}
	auditClient := client.ProvideAuditClient(cfg)
	transactionService := service.NewTransactionService(transactionRepository, auditClient)
	transactionHandler := handlers.NewTransactionHandler(transactionService)
	app := ProvideApp(transactionHandler, cfg)
	return app, nil
}

// wire.go:

// TransactionSet bundles all providers required for Transaction Service
var TransactionSet = wire.NewSet(database.ProviderSet, client.ProviderSet, repository.ProviderSet, service.ProviderSet, handlers.NewTransactionHandler, ProvideApp)
